enyo.depends(
	"$lib/layout/fittable",
	"$lib/layout/slideable",
	"$lib/onyx",
	"../../../../src/js/LabeledItem.js",
	"../../../../src/js/CurrentLocation.js",
	"../../../../src/js/Pullout.js",
  	"../../../../src/js/App.js"
);